### PR TITLE
Navbar

### LINKED ISSUE #114: Add top-level menu bar
Feedback from a potential community member:

> Quick feedback on https://www.developerexperience.us/ - when he scrolled through this it was a bit annoying that there is now top level menu bar that allows him to jump to the individual resources (feels more like dictate not integrate).

@chrifro Can we add links to the top for each section? WDYT design-wise?

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #114

### CODE REVIEW

**Comment by Cahllagerfeld** [comment]
Hey @chrifro, two small things:
- Changing the font-weight on hover causes a small layout-shift, because the box around the element changes, could we maybe work with an underline or a bigger font-color contrast? (See Resources item, the rest of the navitems is unstyled currently)
- We need a mobile menu, because the items will stack on the mobile screen.

**Comment by chrifro** [comment]
Great points @Cahllagerfeld!
- let's stick to the regular font weight and only change the color to black (similar to how we do it on gitpod.io)
- I created a mobile menu as well 🙌 [ See Figma](https://www.figma.com/file/Xt5olSXad7hs5bQP9FF8Pl/DevX?node-id=718%3A410&t=ZqXUfA6VpGA8gZah-1)

**Comment by chrifro** [comment]
Works great. Just one thing: the button size should stay the same. Currently, the width is slightly smaller for the closing button than the menu button
Bildschirmfoto 2022-11-28 um 14 56 51

**Comment by Cahllagerfeld** [comment]
I made the adjustments and fixed a minor bug. Are we ready to 🚢 it then @chrifro ?

**Review by chrifro — APPROVED** [review]
Let's ship it ⛵️

**Pull request merged**
